name: Build UAPKI DLL
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: vcpkg install curl:x86-windows openssl:x86-windows

      - name: Configure CMake
        run: |
          cmake -S library -B build `
          -G "Visual Studio 17 2022" -A Win32 `
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        # Ми додаємо "continue-on-error", бо знаємо, що помилка лише в копіюванні
        continue-on-error: true
        run: cmake --build build --config Release
      - name: Prepare Artifacts
        shell: pwsh
        run: |
          mkdir final_package
          
          # 1. Копіюємо ядро (воно точно тут)
          Copy-Item "build/Release/uapkic.dll" -Destination final_package -ErrorAction SilentlyContinue
          
          # 2. Копіюємо основну бібліотеку з її персональної папки
          Copy-Item "build/library/uapki/Release/uapki.dll" -Destination final_package -ErrorAction SilentlyContinue
          
          # 3. Копіюємо утиліти (вони зазвичай в out або build/bin)
          Get-ChildItem -Path build -Filter "*.exe" -Recurse | Copy-Item -Destination final_package
          
          # 4. Додаємо залежності vcpkg (CURL, OpenSSL)
          Copy-Item "C:/vcpkg/installed/x86-windows/bin/*.dll" -Destination final_package -ErrorAction SilentlyContinue
          
          # 5. ПЕРЕВІРКА: якщо uapki.dll все ще немає, шукаємо її по всьому диску D:
          if (!(Test-Path "final_package/uapki.dll")) {
            Write-Host "Файл не знайдено за прямим шляхом, запускаю глобальний пошук..."
            Get-ChildItem -Path D:/a/UAPKI/UAPKI/build -Filter "uapki.dll" -Recurse | Copy-Item -Destination final_package
          }
          
          ls final_package
      - name: Prepare Deployment Folder
        shell: pwsh
        run: |
          mkdir final_bin
          # Параметр -Recurse змусить скрипт зайти в усі папки (uapki, uapkic, hostapp)
          # і витягнути звідти ВСІ .dll та .exe
          Get-ChildItem -Path build -Filter "*.dll" -Recurse | Copy-Item -Destination final_bin
          Get-ChildItem -Path build -Filter "*.exe" -Recurse | Copy-Item -Destination final_bin
          # Копіюємо залежності vcpkg
          Copy-Item "C:/vcpkg/installed/x86-windows/bin/*.dll" -Destination final_bin -ErrorAction SilentlyContinue
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: UAPKI_Final_Package
          path: final_bin/
